version: 2.1
orbs:
  slack: circle/slack@4.5.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
    run:
      name: Run test
      command: |
        echo "build command"

    slack:
      - slack/notify:
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: This is a test message
          webhook: webhook

workflows:
  your-workflow:
    jobs:
      - build